export const ROUTES = {
  LANDING: '/',
  LOGIN: '/login',
  SUBSCRIBE_PLAN: '/subscribe/plan',
  SUBSCRIBE_REGISTER: '/subscribe/register',
  SUBSCRIBE_VERIFY: '/subscribe/verify',
  SUBSCRIBE_PAYMENT: '/subscribe/payment',
  SUBSCRIBE_SUCCESS: '/subscribe/success',
  RENEWAL: '/renewal',
  DASHBOARD: '/dashboard',
  ENVELOPES: '/envelopes',
  ENVELOPES_NEW: '/envelopes/new',
  ENVELOPE_DETAIL: '/envelopes/:id',
  SIGN: '/sign/:token',
  SIGN_SUCCESS: '/sign/success',
  TEAM: '/team',
  TEMPLATES: '/templates',
  CONTACTS: '/contacts',
  SETTINGS: '/settings',
  NOTIFICATIONS: '/notifications',
} as const;
