export const ROUTES = {
  LANDING: '/',
  LOGIN: '/login',
  SUBSCRIBE_PLAN: '/subscribe/plan',
  SUBSCRIBE_REGISTER: '/subscribe/register',
  SUBSCRIBE_VERIFY: '/subscribe/verify',
  SUBSCRIBE_PAYMENT: '/subscribe/payment',
  SUBSCRIBE_SUCCESS: '/subscribe/success',
  RENEWAL: '/renewal',
  HOME: '/home',
  ENVELOPES: '/envelopes',
  ENVELOPES_NEW: '/envelopes/new',
  ENVELOPE_DETAIL: '/envelopes/:id',
  SIGN: '/sign/:token',
  SIGN_VIEW: '/sign/:token/view',
  SIGN_SUCCESS: '/sign/success',
  CONTACTS: '/contacts',
  ACTIVITY: '/activity',
  NOTIFICATIONS: '/notifications',
  SETTINGS: '/settings',
} as const;
